apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-prometheus-stack
spec:
  destination:
    name: ''
    namespace: grafana
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 66.1.1
    chart: kube-prometheus-stack
  sources: []
  project: default
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: false
    syncOptions:
      - CreateNamespace=true
