apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-dev
  namespace: wordpress
spec:
  project: default
  source:
    chart: wordpress
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 24.0.3
    helm:
      releaseName: wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
